apiVersion: v1
kind: Service
metadata:
  name: buildsignal
  labels:
    app.kubernetes.io/name: buildsignal
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: buildsignal
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
